### ISSUE TITLE
py39-duckdb missing from images

### ISSUE THREAD

**Issue by maurice-w** [yrzr/opnsense-tools#1] opened 2023-07-24 16:04 UTC
`py39-duckdb` and some dependencies are missing from `OPNsense-23.1.11-vm-aarch64.vmdk.xz` and `OPNsense-23.7.r1-vm-aarch64.vmdk.xz`. This package is required for Unbound DNS reporting (Reporting: Settings: Unbound DNS reporting). It is available from your repository though and can be installed with `pkg install py39-duckdb`, which makes DNS reporting work.

I was just wondering if you have an idea why it's not included in the images.

Cheers & thanks for all your work!
Maurice

**Comment by yrzr** [comment] 2023-07-26 10:51
Hi Maurice. You have a good insight. I myself can hardly find a problem like this.

The problem is caused because the core only depends on `py39-duckdb` on AMD64.

https://github.com/opnsense/core/blob/77f9b43234f169cf809ec606aa06ead0de4043b2/Makefile#L131

I think it makes no sense to keep the package on amd64 only since the packages could be built on aarch64. And I have created this [pull request](https://github.com/opnsense/core/pull/6686).

**Comment by yrzr** [comment] 2023-07-27 03:13
merged

**Closed as completed by yrzr** 2023-07-27 03:13 UTC

**Comment by maurice-w** [comment] 2023-07-27 17:57
Great, thanks! Looking forward to 23.7 images with duckdb.

**Comment by maurice-w** [comment] 2023-08-01 20:37
I did build an OPNsense 23.7-aarch64 VM image from source and can confirm that Unbound DNS reporting now works out of the box. 👍
